### ISSUE TITLE
falling-branch disable colliders at specified time

### ISSUE THREAD

**Issue by etzl** [DarkFutureStudio/Lonely#1]
colliders wrapped in array. The point is disable them one by one in specified **time**
@M-Pages @sinnerman0 see if you can help this out 👍 
and also comment you opinion and assign who want to do animation and graphic part or ...

**Comment by etzl** [comment]
So what is your opinion @M-Pages and @sinnerman0 should we keep this in game or not?

**Comment by M-Pages** [comment]
I think it's already done right?
