### ISSUE TITLE
Trigger collider slow player down

### ISSUE THREAD

**Issue by etzl** [DarkFutureStudio/Lonely#10]
As #1 made a **Bug** occurs that when player enters trigger it slow down a bit and then works ok

**Comment by M-Pages** [comment]
which branch?

**Comment by etzl** [comment]
> 
> 
> which branch?

Now in the develop
i suspect that it is because player movement because with your new player movement it works fine (I think)

**Comment by etzl** [comment]
using your *Player Movement* fixed the problem...
