### ISSUE TITLE
Die Sun Of The Bitch

### ISSUE THREAD

**Issue by etzl** [DarkFutureStudio/Lonely#12]
#1 after falling player will die and the game is over...

**Comment by M-Pages** [comment]
hmmm.... just falling?I mean the palyer can die just by falling or what?

**Comment by etzl** [comment]
> 
> 
> hmmm.... just falling?I mean the palyer can die just by falling or what?

do you mean dying should be hard? 🌝  or should we have other plans like GRIS???!

**Comment by M-Pages** [comment]
Noooo...not like gris but I think there should be a lot of things that player should really be careful
