### ISSUE TITLE
Shape shif has a problem with camera

### ISSUE THREAD

**Issue by M-Pages** [DarkFutureStudio/Lonely#16]
### camera doesn't follow the bird!
*The problem is when the player shape shifts the object will destroy so the camera won't follow it after shape shift

**Comment by etzl** [comment]
can you shape shift via sprite render? that way it just shifting without destroy it

**Comment by M-Pages** [comment]
hmmm...yes maybe but I need to change a lot of things

**Comment by sinnerman0** [comment]
I think we could change sprites instead change or destroy object.

**Comment by etzl** [comment]
> 
> 
> I think we could change sprites instead change or destroy object.

Yes we have a branch *'shapeShift'* that do the same, it's on @M-Pages to do what is better for this issue...

**Comment by M-Pages** [comment]
Yes thank you it really did help, I think it's fixed now :)
