### ISSUE TITLE
Part of riddle

### ISSUE THREAD

**Issue by etzl** [DarkFutureStudio/Lonely#20]
A collectable objects that interact with player and shows a bunch of *letters* 🔠

**Comment by M-Pages** [comment]
I need an example...I can't completely understand

**Comment by etzl** [comment]
> 
> 
> I need an example...I can't completely understand

I'm working on it once it done it will publish as a branch... checkout it out

**Comment by M-Pages** [comment]
ok ty :)

**Comment by etzl** [comment]
It's published so i am waiting for your answers 🚶

**Comment by M-Pages** [comment]
I told you in telegram so I won't tell you here :)
