### ISSUE TITLE
Error in unity

### ISSUE THREAD

**Issue by etzl** [DarkFutureStudio/Lonely#3]
project have a bug in it that says: 
`
System.Reflection.ReflectionTypeLoadException was thrown
`

**Comment by etzl** [comment]
I believe this relate to ***Cinemachine*** and when we use **git** with it, it throws exception

**Comment by M-Pages** [comment]
yeah I have a lot of problems with cinemachine too

**Comment by etzl** [comment]
Looks like the error is because using git to share **packages** too, i updated gitattributes to solve this once @sinnerman0 that have complete  *Cinemachine* commit and push again it will be ok *(I think so and i hope so)* :godmode: -- branch develop --

**Comment by etzl** [comment]
The bug is fixed the cause of this would be two possibility:
1. git tracked packages and did it's part but when it came to our project unity didn't find it package and it is just **something** *(unity thought)*
2. git didn't done it's part properly so some part of package is missing and unity didn't recognized its package

if **FIRST** possibility is true the problem come from *unity-package-manager* and we can't do anything about it,
but if **SECOND** possibility is true then the problem come from us because we tell the git how to track files... 

if the *second* answer is correct we have two solution:
1. tell git => **Do not track package files**, then we have our scene and everyone have to install cinemachine separately ==> can cause damage to components *(missing scripts)*
2. track files like project nowadays and if it didn't cause anything else we continue *like nothing happened* ((cause fixing from this step is going to damage like first solution)) but if we do this in start *where not important thing done into cinemachine* we can install cinemachine separately and fix *script missing* ((that doesn't cost much)) and work fine until god take us from the earth 🌎 

I have an idea that if someone take this new commits on `develop` branch and still have the problem it's because unity **package-manager**, i updated *gitattributes* and we shouldn't -- in theory -- have any problem with **SECOND** possibility...
