### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by etzl** [DarkFutureStudio/Lonely#9]
Find out what the game theme should be

**Comment by etzl** [comment]
- **Life**
- **Dreams & Nightmare**
- **Dreams**
- **Shadows are always with us**
- **Zero To Hero**

**Comment by etzl** [comment]
What i found on theme, but i **UNDERLINE** the first one =>
- Life = Dreams & Nightmare

**Comment by M-Pages** [comment]
we should discuss this

**Comment by etzl** [comment]
- The point of shadow is we don't know who we are, and we are looking for our identity 
   - every riddle is going to tell us **who am i**

**Comment by M-Pages** [comment]
hmmm....that's pretty good.
can you tell us your idea in work...I mean where we can understand it

**Comment by etzl** [comment]
Looks like the theme is the last one now so I **close** this issue...
